name: 'Release'
description: 'TODO'
runs:
    using: 'node12'
    main: 'dist/index.js'
outputs:
    tag:
        description: 'Tag to publish (optional)'
    version:
        description: 'Version to publish'
