name: pull-request
on: pull_request
jobs:
    local-action:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel running workflows
              uses: styfle/cancel-workflow-action@0.6.0
              with:
                  access_token: ${{ github.token }}
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Run local action
              uses: ./.github/actions/local-action
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel running workflows
              uses: styfle/cancel-workflow-action@0.6.0
              with:
                  access_token: ${{ github.token }}
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Read node version
              id: nvm
              run: echo "::set-output name=version::$(cat .nvmrc)"
            - name: Set node version
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ steps.nvm.outputs.version }}
            - name: Cache node_modules
              uses: actions/cache@v2
              id: cache-node-modules
              with:
                  path: '**/node_modules'
                  key: dependencies-v1-${{ hashFiles('**/yarn.lock') }}
            - name: Install dependencies
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile
            - name: Run tests
              run: yarn test
