name: release
on:
    release:
        types: [created]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.release.target_commitish }}
            - name: Release
              id: release
              uses: ./.github/actions/release
            - name: Read node version
              id: nvm
              run: echo "::set-output name=version::$(cat .nvmrc)"
            - name: Set node version
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ steps.nvm.outputs.version }}
            - name: Cache node_modules
              uses: actions/cache@v2
              id: cache-node-modules
              with:
                  path: '**/node_modules'
                  key: dependencies-v1-${{ hashFiles('**/yarn.lock') }}
            - name: Install dependencies
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile
            - name: OUTPUT
              env:
                  PUBLISH_COMMAND: ${{steps.release.outputs.publish_command}}
              run: |
                  echo "Publish command: $PUBLISH_COMMAND"
            # Run build step here, if needed.
            # - name: Publish
            #   run: ${{ steps.release.outputs.command }}
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
