name: release
on:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel running workflows
              uses: styfle/cancel-workflow-action@0.6.0
              with:
                  access_token: ${{ github.token }}
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.release.target_commitish }}
            # - name: Read node version
            #   id: nvm
            #   run: echo "::set-output name=version::$(cat .nvmrc)"
            # - name: Set node version
            #   uses: actions/setup-node@v1
            #   with:
            #       node-version: ${{ steps.nvm.outputs.version }}
            # - name: Cache node_modules
            #   uses: actions/cache@v2
            #   id: cache-node-modules
            #   with:
            #       path: '**/node_modules'
            #       key: dependencies-v1-${{ hashFiles('**/yarn.lock') }}
            # - name: Instal dependencies
            #   if: steps.cache-node-modules.outputs.cache-hit != 'true'
            #   run: yarn install --frozen-lockfile
            - name: Read package.json version
              uses: ashley-taylor/read-json-property-action@v1.0
              id: package-json-version
              with:
                  path: package.json
                  property: version
            - name: RELEASE
              id: release-version
              run: echo "::set-output name=value::$(echo "${GITHUB_REF:11}")"
            - name: PACKAGE.JSON
              run: echo ${{ steps.package-json-version.outputs.value }}
            - name: SUCCESS
              if: steps.package-json-version.outputs.value == steps.release-version.outputs.value
              run: echo 'SUCCESS!!!'
            - name: FAIL
              if: steps.package-json-version.outputs.value != steps.release-version.outputs.value
              run: |
                  echo 'FAIL!!!'
                  exit 1
