name: release
on:
    release:
        types: [created]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.release.target_commitish }}
            - name: Validate and extract release information
              id: release
              uses: manovotny/github-releases-for-automated-package-publishing-action@v1.0.0
            - name: Set node version
              uses: actions/setup-node@v2
              with:
                  always-auth: true
                  node-version: '12.x'
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Publish version
              if: steps.release.outputs.tag == ''
              run: yarn publish --new-version ${{ steps.release.outputs.version }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Publish version with tag
              if: steps.release.outputs.tag != ''
              run: yarn publish --new-version ${{ steps.release.outputs.version }} --tag ${{ steps.release.outputs.tag }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
