name: release
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel running workflows
              uses: styfle/cancel-workflow-action@0.6.0
              with:
                  access_token: ${{ github.token }}
            - name: Checkout repo
              uses: actions/checkout@v2
              # with:
              # ref: ${{ github.event.release.target_commitish }}
            # - name: Read node version
            #   id: nvm
            #   run: echo "::set-output name=version::$(cat .nvmrc)"
            # - name: Set node version
            #   uses: actions/setup-node@v1
            #   with:
            #       node-version: ${{ steps.nvm.outputs.version }}
            # - name: Cache node_modules
            #   uses: actions/cache@v2
            #   id: cache-node-modules
            #   with:
            #       path: '**/node_modules'
            #       key: dependencies-v1-${{ hashFiles('**/yarn.lock') }}
            # - name: Instal dependencies
            #   if: steps.cache-node-modules.outputs.cache-hit != 'true'
            #   run: yarn install --frozen-lockfile
            - name: Read package.json version
              id: version
              uses: notiz-dev/github-action-json-property@0.1.0
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - name: TESTING
              run: echo ${{ steps.version.outputs.prop }}
              # github.event.release.tag_name
